---
- name: finding a replacing acls
  hosts: cisco
  gather_facts: false

  tasks:
    - name: Load new acl into device
      cisco.ios.ios_config:
        lines:
          - 10 permit ip host 192.0.2.6 any log
          - 20 permit ip host 192.0.2.7 any log
          - 30 permit ip host 192.0.2.8 any log
          - 40 permit ip host 192.0.2.9 any log
          - 50 permit ip host 192.0.2.10 any log
        parents: ip access-list extended test
        before: no ip access-list extended test
        match: exact