---
- name: Connecting to routers
  hosts: cisco
  connection: network_cli
  #connection: httpapi - NXOS supports network_cli and/or httpapi connection plug-ins. If one doesn't work, try the other.
  gather_facts: false

  collections:
    - cisco.nxos

  tasks:
    - name: Merge provided configuration with device configuration.
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: Ethernet1/6
            ipv4:
              - address: 192.168.1.1/24
                tag: 5
              - address: 10.1.1.1/24
                secondary: true
                tag: 10
            ipv6:
              - address: fd5d:12c9:2201:2::1/64
                tag: 6
          - name: Ethernet1/7.42
            redirects: false
            unreachables: false
# https://console.redhat.com/ansible/automation-hub/repo/published/cisco/nxos/content/module/nxos_l3_interfaces/
