---
- name: Connecting to routers
  hosts: cisco
  connection: network_cli
  #connection: httpapi - NXOS supports network_cli and/or httpapi connection plug-ins. If one doesn't work, try the other.
  gather_facts: false

  collections:
    - cisco.nxos

  tasks:
    - name: Merge the provided configuration with the existing running configuration
      cisco.nxos.nxos_ospfv2:
        config:
          processes:
            - process_id: 100
              router_id: 203.0.113.20
            - process_id: 102
              router_id: 198.51.100.1
              areas:
                - area_id: "0.0.0.100"
                  filter_list:
                    - route_map: rmap_1
                      direction: in
                    - route_map: rmap_2
                      direction: out
                  ranges:
                    - prefix: 198.51.100.64/27
                      not_advertise: true
                    - prefix: 198.51.100.96/27
                      cost: 120
                - area_id: "0.0.0.101"
                  authentication:
                    message_digest: true
              redistribute:
                - protocol: eigrp
                  id: 120
                  route_map: rmap_1
                - protocol: direct
                  route_map: ospf102-direct-connect
              vrfs:
                - vrf: zone1
                  router_id: 198.51.100.129
                  redistribute:
                    - protocol: static
                      route_map: zone1-static-connect
                  summary_address:
                    - prefix: 198.51.100.128/27
                      tag: 121
                    - prefix: 198.51.100.160/27
                  areas:
                    - area_id: "0.0.0.102"
                      nssa:
                        default_information_originate: true
                        no_summary: true
                    - area_id: "0.0.0.103"
                      nssa:
                        no_summary: true
                        translate:
                          type7:
                            always: true
                - vrf: zone2
                  auto_cost:
                    reference_bandwidth: 45
                    unit: Gbps
        state: merged
# https://console.redhat.com/ansible/automation-hub/repo/published/cisco/nxos/content/module/nxos_ospfv2/
